### ISSUE TITLE
Rename this tool as TeXBuildPkg

### ISSUE THREAD

**Issue by lvjr** [lvjr/texbuildpkg#6]
I need to finished the following tasks first:

- [x] Add `generate` target (#7)
- [x] Rewrite `check` and `save` targets (#5)
- [ ] Add `bench` target (#3)
- [ ] Add `typeset` target (#4)

Then I will rename this tool from `ppmcheckpdf` to `texbuildpkg`.

**Comment by lvjr** [comment]
I have decided to do renaming first. Done.
